DROP TABLE IF EXISTS peer_name;
DROP TABLE IF EXISTS message_body;
DROP TABLE IF EXISTS message;
DROP TABLE IF EXISTS send_message_event;
DROP TABLE IF EXISTS event;
DROP TABLE IF EXISTS peer;
DROP TABLE IF EXISTS entity;
